---
title:    Software licensing primer
subtitle: A short introduction and reference to open source software licenses

author:   Attila Gulyas
date:     September 30, 2017

link-citations:  true
urlcolor: blue
...
